module.exports = {
  AI: {
    OBJECTIONS_MODEL: 'claude-haiku-4-5-20251001',
    OBJECTIONS_MAX_TOKENS: 1024,
    OBJECTIONS_TIMEOUT_MS: 30000
  },
  OBJECTION_TYPES: {
    PENSAR_CON_PAREJA: 'PENSAR_CON_PAREJA',
    CARO_ESPERAR: 'CARO_ESPERAR',
    COMPARAR_PROYECTOS: 'COMPARAR_PROYECTOS',
    SOLO_INFO: 'SOLO_INFO',
    VER_PRESENCIAL: 'VER_PRESENCIAL',
    NUEVA: 'NUEVA'
  },
  CLOSING_TYPES: {
    ASUMIDO: 'ASUMIDO',
    ALTERNATIVO: 'ALTERNATIVO',
    URGENCIA: 'URGENCIA',
    PREGUNTA_INVERSA: 'PREGUNTA_INVERSA'
  },
  PROFILE_TYPES: {
    VIVIENDA_PROPIA: 'VIVIENDA_PROPIA',
    PRIMERA_INVERSION: 'PRIMERA_INVERSION',
    INVERSIONISTA: 'INVERSIONISTA',
    EXPERTO: 'EXPERTO'
  }
};
